setopt interactivecomments
setopt no_share_history

# confiugre oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=( git zsh-kubectl-prompt virtualenv )
source $ZSH/oh-my-zsh.sh

# kube prompt
autoload -U colors; colors
source ~/.oh-my-zsh/custom/plugins/zsh-kubectl-prompt/kubectl.zsh
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'

# remove user@host from prompt
prompt_context() {}

alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias gvim='gvim --servername ${VSRV:-GVIM} --remote-tab ${1:-""}'
alias sgrep="grep --binary-files=without-match --exclude-dir='.svn'"
alias sdiff="svn diff --diff-cmd kdiff3"
alias gdiff="git diff --color-words --word-diff-regex=. --no-index"
alias ack=ack-grep
alias vi="vim -u NONE" # do not load vimrc - super fast
which colordiff 2>&1 > /dev/null && alias diff=colordiff
alias -g ND='*(/om[1])' # newest directory
alias -g NF='*(.om[1])' # newest file
kubeuse() { kubectl config use-context ${1:-minikube} --namespace=${2:-default} }
kubesetnm() { kubectl config set-context ${1:-minikube} --namespace=${2:-default} }
alias k=kubectl

export EDITOR=vim
export CSCOPE_LINEFLAG_AFTER_FILE=yes
export ANDROID_SDK=$HOME/Android/Sdk
export ANDROID_NDK=$HOME/Programs/ndk
export PATH=$HOME/bin:$HOME/.local/bin:$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools:$HOME/bin/scripts:$HOME/bin/privscripts
export PAGER='less -r'
#export PYTHONPATH=$PYTHONPATH:~/py-lib
export GOPATH=$HOME/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH
. ~/bin/bin.paths
serial ()
{
  test -w /dev/ttyUSB0 || sudo chmod 666 /dev/ttyUSB0;
  screen /dev/ttyUSB0 115200
}

# editing of commands
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

bindkey -v

eval `dircolors ~/.dircolors/dircolors.ansi-dark`

# solarized colors for grep
unset GREP_COLOR
export GREP_COLORS='01;33'

# fix colors for vim in tmux
if [ -n "$TMUX" ]; then
  export TERM="screen-256color"
else
  export TERM="xterm-256color"
fi

bindkey '^R' history-incremental-search-backward
bindkey '^R' history-incremental-pattern-search-backward
DISABLE_AUTO_TITLE=true

# marks
export MARKPATH=$HOME/.marks
function jump { 
  cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark { 
  mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark { 
  rm -i "$MARKPATH/$1"
}
function marks {
  ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}

function _completemarks {
  reply=($(ls $MARKPATH))
}

compctl -K _completemarks jump
compctl -K _completemarks unmark

test -n "$DISPLAY" && synclient -l >/dev/null 2>&1 && synclient VertEdgeScroll=0 # disable touchpad scroll

if [ -f ~/.zshrc_local ]
then
  . ~/.zshrc_local
fi

fs() {
    find . -name \*"$1"
}

fp() {
    find . -name "$1"\*
}

fe() {
    find . -name "$1"
}

if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi
true
