setopt interactivecomments

# confiugre oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh

alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias gvim='gvim --servername ${VSRV:-GVIM} --remote-tab ${1:-""}'
alias sgrep="grep --binary-files=without-match --exclude-dir='.svn'"
alias sdiff="svn diff --diff-cmd kdiff3"
alias gdiff="git diff --color-words --word-diff-regex=. --no-index"
alias ack=ack-grep
alias vi="vim -u NONE" # do not load vimrc - super fast
which colordiff 2>&1 > /dev/null && alias diff=colordiff
alias -g ND='*(/om[1])' # newest directory
alias -g NF='*(.om[1])' # newest file

export EDITOR=vim
export CSCOPE_LINEFLAG_AFTER_FILE=yes
export ANDROID_SDK=$HOME/Programs/sdk
export PATH=$HOME/bin:$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools
export PAGER='less -r'
export PYTHONPATH=$PYTHONPATH:~/py-lib
export GOPATH=$HOME/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH
serial ()
{
  test -w /dev/ttyUSB0 || sudo chmod 666 /dev/ttyUSB0;
  screen /dev/ttyUSB0 115200
}

# editing of commands
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

bindkey -v

eval `dircolors ~/.dircolors/dircolors.ansi-dark`

# solarized colors for grep
unset GREP_COLOR
export GREP_COLORS='01;33'

# fix colors for vim in tmux
if [ -n "$TMUX" ]; then
  export TERM="screen-256color"
else
  export TERM="xterm-256color"
fi

bindkey '^R' history-incremental-search-backward
bindkey '^R' history-incremental-pattern-search-backward
DISABLE_AUTO_TITLE=true

# marks
export MARKPATH=$HOME/.marks
function jump { 
  cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark { 
  mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark { 
  rm -i "$MARKPATH/$1"
}
function marks {
  ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}

function _completemarks {
  reply=($(ls $MARKPATH))
}

compctl -K _completemarks jump
compctl -K _completemarks unmark

test -n "$DISPLAY" && synclient -l >/dev/null 2>&1 && synclient VertEdgeScroll=0 # disable touchpad scroll

if [ -f ~/.zshrc_local ]
then
  . ~/.zshrc_local
fi
